name: Node.js Code Check
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Button für manuelles Auslösen der Pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Node.js einrichten
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - name: Alle JavaScript-Dateien mit >node --check< prüfen
      run: |
        zaehler=0
        while IFS= read -r file
        do
          node --check "$file"
          let zaehler+=1
        done < <(find . -name "*.js")
        echo "Anzahl js-Dateien mit Nodejs geprüft: $zaehler"
